### PR TITLE
Reply voting -- voting added, 

### PR DESCRIPTION
**Pull request by rashikcolgate**
post render edit spec fails, someone please look into this

### CODE REVIEW

**Review by Eliheakins — CHANGES_REQUESTED** [review]
Still unable to seed
bin/rails aborted!
ActiveRecord::StatementInvalid: SQLite3::SQLException: table votes has no column named post_id (ActiveRecord::StatementInvalid)
/mnt/c/Users/elida/Computer Science/software-engineering/Stack-Overflow-Clone/db/seeds.rb:81:in `block in <main>'
/mnt/c/Users/elida/Computer Science/software-engineering/Stack-Overflow-Clone/db/seeds.rb:80:in `<main>'

Caused by:
SQLite3::SQLException: table votes has no column named post_id (SQLite3::SQLException)
/mnt/c/Users/elida/Computer Science/software-engineering/Stack-Overflow-Clone/db/seeds.rb:81:in `block in <main>'
/mnt/c/Users/elida/Computer Science/software-engineering/Stack-Overflow-Clone/db/seeds.rb:80:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)

**Comment by rashikcolgate** [comment]
> Still unable to seed bin/rails aborted! ActiveRecord::StatementInvalid: SQLite3::SQLException: table votes has no column named post_id (ActiveRecord::StatementInvalid) /mnt/c/Users/elida/Computer Science/software-engineering/Stack-Overflow-Clone/db/seeds.rb:81:in `block in <main>' /mnt/c/Users/elida/Computer Science/software-engineering/Stack-Overflow-Clone/db/seeds.rb:80:in `
> 
> '
> Caused by: SQLite3::SQLException: table votes has no column named post_id (SQLite3::SQLException) /mnt/c/Users/elida/Computer Science/software-engineering/Stack-Overflow-Clone/db/seeds.rb:81:in `block in <main>' /mnt/c/Users/elida/Computer Science/software-engineering/Stack-Overflow-Clone/db/seeds.rb:80:in `
> 
> '
> Tasks: TOP => db:seed
> (See full trace by running task with --trace)

U need to db drop then re-migrate then seed again. this is a recurring issue

**Review by Eliheakins — APPROVED** [review]
Weirdly it has that issue if I run all of the commands together (rails db:drop db:migrate db:seed) but now when ran one at a time

**Review by Eliheakins — CHANGES_REQUESTED** [review]
Fix merge conflict and make sure everything still works and should be good to go

**Pull request closed without merging**
