### PR TITLE
Spec voting

### PR DESCRIPTION
**Pull request by rashikcolgate**
Specs added, button edited for voting, voting logic changed to add vote removal (realised it was not accounted for previously)

### CODE REVIEW

**Review by JacobKrehbiel03 — APPROVED** [review]
Everything seems to work as intended and the tests seem to assess all the things they need to.  The seeds were updated to work with the new changes to which is good. I don't think there is anything to me that seems to need to be changed for this to be merged.

**Comment by Eliheakins** [comment]
> Everything seems to work as intended and the tests seem to assess all the things they need to. The seeds were updated to work with the new changes to which is good. I don't think there is anything to me that seems to need to be changed for this to be merged.

Can you wait until the merge is done before approval as merge conflicts have been causing issues with functionality breaking and tests breaking?

**Comment by rashikcolgate** [comment]
> > Everything seems to work as intended and the tests seem to assess all the things they need to. The seeds were updated to work with the new changes to which is good. I don't think there is anything to me that seems to need to be changed for this to be merged.
> 
> Can you wait until the merge is done before approval as merge conflicts have been causing issues with functionality breaking and tests breaking?

Failing Scenarios:
cucumber features/support/tag_post_assoc.feature:12 # Scenario: Create Post with null tag should create post
cucumber features/support/tag_post_assoc.feature:18 # Scenario: Create post with tag should create post and post should be visible on the tag's show page
cucumber features/support/tag_post_assoc.feature:28 # Scenario: Editing a post should allow a new tag to be chosen and update appropriately
cucumber features/support/tag_post_assoc.feature:44 # Scenario: Posts with multiple tags should be created
cucumber features/support/tag_post_assoc.feature:57 # Scenario: Tags on posts should be link to tag page
cucumber features/support/tag_post_assoc.feature:64 # Scenario: Deleting tags should not delete posts

these are the ones that are breaking after resolving merge conflicts

**Comment by naheedaakhtar** [comment]
Do you mean that before the merge conflicts you had these errors and then after you resolved contacts they're no longer there? Because I just ran cucumber tests & they look fine

**Pull request merged**
