### PR TITLE
Post Tag Multiple Association

### PR DESCRIPTION
**Pull request by JacobKrehbiel03**
I added functionality for posts to have multiple tags.
I also added a small feature where the tags are links to that tag's page.

The text in the tags is blue because it is a link. This can be changed by adding a style to the html tag for the link or creating a new css sheet. I was not sure what to prefer as the change is simply the text color, but I wasn't sure what was preferred for such a small style choice.

### CODE REVIEW

**Review by Eliheakins — CHANGES_REQUESTED** [review]
Couple things that need addressed after merging main in:
- I think the merge into main broke the form to select multiple tags, I would look at the merge I did. It had a merge conflict and it might've been handled incorrectly for your new implementation 
- Can you fix seeds, I tried to but was having some issues

**Comment by JacobKrehbiel03** [comment]
I think the edits in my commit caught everything strange that got changed. 
I also changed the seeds to work now.

**Review by Eliheakins — APPROVED** [review]

**Review by Eliheakins — CHANGES_REQUESTED** [review]
I am still having issues selecting multiple tags for a post, this was happening previous to my changes to the CSS, but it should be a lot clearer now when multiple tags are selected

**Comment by JacobKrehbiel03** [comment]
I updated the controller/tests for the new checkbox version. I was able to select multiple items before, but it was by holding control and then using spacebar on each item that I wanted to select, which I believe is how the select box is used to select multiple when the parameter is set to multiple allowed. However, this is pretty unintuitive, so it does make more sense to swap to the more easy to work with checkboxes anyway.

**Review by Eliheakins — APPROVED** [review]

**Pull request merged**
